--====================================================================== 
--[[ 
* ReaScript Name: kawa_MAIN_RenderSelectedItemsToNewTrack. 
* Version: 2017/01/16 
* Author: kawa_ 
* Author URI: http://forum.cockos.com/member.php?u=105939 
* Repository: BitBucket - kawaCat - ReaScript-M2B 
* Repository URI: https://bitbucket.org/kawaCat/reascript-m2bpack/ 
--]] 
--====================================================================== 
local a=0;local m=reaper.CountSelectedMediaItems(a);local i="kawa MAIN selected Item Render New Track"local c=40914 local I=40289 local p=40290 local M=41720 local function s(e)local t=reaper.CountSelectedMediaItems(e);local i=reaper.GetProjectLength(e);local r={}local a={}local n=0;while(n<t)do local t=reaper.GetSelectedMediaItem(e,n);local l=reaper.GetMediaItemTrack(t);local e=reaper.GetMediaTrackInfo_Value(l,"IP_TRACKNUMBER");if(a[e]==nil)then a[e]={}local r=reaper.CountTrackMediaItems(l);local t=0;while(t<r)do local r=reaper.GetTrackMediaItem(l,t)local n=reaper.GetMediaItemInfo_Value(r,"D_POSITION")local o=reaper.GetMediaItemInfo_Value(r,"D_LENGTH")local l={mediaItem=r,startTime=n,length=o,endTime=n+o,mediaItemIdx=reaper.GetMediaItemInfo_Value(r,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l};table.insert(a[e],l);t=t+1;end table.sort(a[e],function(e,a)return(e.startTime>a.startTime);end);end local o=reaper.GetMediaItemInfo_Value(t,"D_POSITION")local d=reaper.GetMediaItemInfo_Value(t,"D_LENGTH")local t={mediaItem=t,startTime=o,length=d,endTime=o+d,mediaItemIdx=reaper.GetMediaItemInfo_Value(t,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l,nextItemStartTime=nil,nextMediaItem=nil};local l=i;local o=nil for a,e in ipairs(a[e])do if(e.mediaItemIdx==t.mediaItemIdx)then t.nextItemStartTime=l;t.nextMediaItem=o;end l=e.startTime;o=e;end if(r[e]==nil)then r[e]={}end table.insert(r[e],t);n=n+1;end return a,r end local function l(t)local e=true;local a=reaper.CountSelectedMediaItems(a);if(a>t)then reaper.ShowMessageBox("over "..tostring(t).." clip num .\nstop process","stop.",0)e=false;end return e end if(l(20)==false)then return end if(m>0)then reaper.Undo_BeginBlock();local t,e=s(a)for t,e in pairs(e)do for t,e in ipairs(e)do local t=e.mediaTrack local e=e.mediaItem reaper.Main_OnCommand(I,a)reaper.SetMediaItemSelected(e,1)reaper.SetOnlyTrackSelected(t,1);reaper.Main_OnCommand(c,a)reaper.Main_OnCommand(p,a)reaper.Main_OnCommand(M,a)end end reaper.Undo_EndBlock(i,-1);reaper.UpdateArrange();end
