--====================================================================== 
--[[ 
* ReaScript Name: kawa_MAIN_BasePitchTuning. 
* Version: 2017/01/16 
* Author: kawa_ 
* Author URI: http://forum.cockos.com/member.php?u=105939 
* Repository: BitBucket - kawaCat - ReaScript-M2B 
* Repository URI: https://bitbucket.org/kawaCat/reascript-m2bpack/ 
--]] 
--====================================================================== 
local t=0;local d="kawa MAIN Change Base Pitch Tuning";local c=reaper.CountSelectedMediaItems(t);local e=40297 local m=40289 local s=41588 local r=200;local function l(a)local e=true;local t=reaper.CountSelectedMediaItems(t);if(t>a)then reaper.ShowMessageBox("over "..tostring(a).." clip num .\nstop process","stop.",0)e=false;end return e end if(l(r)==false)then return end function string:split(e)local a,e=e or":",{}local a=string.format("([^%s]+)",a)self:gsub(a,function(a)e[#e+1]=a end)return e end local function I()local t,e=reaper.GetUserInputs("selection item transpose",7,"base Pitch,Glue item 0 or 1","440,0,--,--,--,--,--")local a=440;local l=0 if(t)then e=string.gsub(e," ","")local e=e:split(",");local t=e[1];a=math.floor((tonumber(t)or 440));l=tonumber(e[2])end return t,a,l end local function u(e)local t=reaper.CountSelectedMediaItems(e);local c=reaper.GetProjectLength(e);local o={}local a={}local n=0;while(n<t)do local t=reaper.GetSelectedMediaItem(e,n);local l=reaper.GetMediaItemTrack(t);local e=reaper.GetMediaTrackInfo_Value(l,"IP_TRACKNUMBER");if(a[e]==nil)then a[e]={}local t=reaper.CountTrackMediaItems(l);local r=0;while(r<t)do local t=reaper.GetTrackMediaItem(l,r)local o=reaper.GetMediaItemInfo_Value(t,"D_POSITION")local n=reaper.GetMediaItemInfo_Value(t,"D_LENGTH")local t={mediaItem=t,startTime=o,length=n,endTime=o+n,mediaItemIdx=reaper.GetMediaItemInfo_Value(t,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l};table.insert(a[e],t);r=r+1;end table.sort(a[e],function(e,a)return(e.startTime>a.startTime);end);end local i=reaper.GetMediaItemInfo_Value(t,"D_POSITION")local r=reaper.GetMediaItemInfo_Value(t,"D_LENGTH")local t={mediaItem=t,startTime=i,length=r,endTime=i+r,mediaItemIdx=reaper.GetMediaItemInfo_Value(t,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l,nextItemStartTime=nil,nextMediaItem=nil};local r=c;local l=nil for a,e in ipairs(a[e])do if(e.mediaItemIdx==t.mediaItemIdx)then t.nextItemStartTime=r;t.nextMediaItem=l;end r=e.startTime;l=e;end if(o[e]==nil)then o[e]={}end table.insert(o[e],t);n=n+1;end return a,o end local function a(e)local e=reaper.GetTake(e,reaper.GetMediaItemInfo_Value(e,"I_CURTAKE"))return e;end local function r(e)return 1200*math.log(e/440)/math.log(2);end local function e(e)return math.exp(e/1200*math.log(2))*440;end local function l(l,e)local t=e or 440;local e=a(l);if(e==nil)then return end local a=r(t);local a=a*.01;reaper.SetMediaItemTakeInfo_Value(e,"D_PITCH",a)end local function r(e)local a=a(e);if(a==nil)then return end reaper.PreventUIRefresh(3)reaper.Main_OnCommand(m,t)reaper.SetMediaItemSelected(e,true)reaper.Main_OnCommand(s,t)reaper.PreventUIRefresh(-1)end local e,o,n=I()if(e)then if(c>0)then reaper.Undo_BeginBlock();local a,e=u(t)local a=reaper.GetCursorPosition();for a,e in pairs(e)do for a,e in ipairs(e)do l(e.mediaItem,o)if(n==true)then r(e.mediaItem)end end end reaper.SetEditCurPos(a,true,false)reaper.PreventUIRefresh(-1)reaper.Undo_EndBlock(d,-1);reaper.UpdateArrange();end end
