--====================================================================== 
--[[ 
* ReaScript Name: kawa_MAIN_ColorSelectedItemHue. 
* Version: 2017/01/16 
* Author: kawa_ 
* Author URI: http://forum.cockos.com/member.php?u=105939 
* Repository: BitBucket - kawaCat - ReaScript-M2B 
* Repository URI: https://bitbucket.org/kawaCat/reascript-m2bpack/ 
--]] 
--====================================================================== 
local I=0 local s=reaper.CountSelectedMediaItems(I);math.randomseed(reaper.time_precise()*os.time()/1e3)local f="kawa MAIN Selected Item Hue";local function h(e)local a=reaper.CountSelectedMediaItems(e);local d=reaper.GetProjectLength(e);local r={}local t={}local n=0;while(n<a)do local a=reaper.GetSelectedMediaItem(e,n);local l=reaper.GetMediaItemTrack(a);local e=reaper.GetMediaTrackInfo_Value(l,"IP_TRACKNUMBER");if(t[e]==nil)then t[e]={}local a=reaper.CountTrackMediaItems(l);local n=0;while(n<a)do local a=reaper.GetTrackMediaItem(l,n)local r=reaper.GetMediaItemInfo_Value(a,"D_POSITION")local i=reaper.GetMediaItemInfo_Value(a,"D_LENGTH")local a={mediaItem=a,startTime=r,length=i,endTime=r+i,mediaItemIdx=reaper.GetMediaItemInfo_Value(a,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l};table.insert(t[e],a);n=n+1;end table.sort(t[e],function(t,e)return(t.startTime>e.startTime);end);end local o=reaper.GetMediaItemInfo_Value(a,"D_POSITION")local i=reaper.GetMediaItemInfo_Value(a,"D_LENGTH")local a={mediaItem=a,startTime=o,length=i,endTime=o+i,mediaItemIdx=reaper.GetMediaItemInfo_Value(a,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l,nextItemStartTime=nil,nextMediaItem=nil};local i=d;local l=nil for t,e in ipairs(t[e])do if(e.mediaItemIdx==a.mediaItemIdx)then a.nextItemStartTime=i;a.nextMediaItem=l;end i=e.startTime;l=e;end if(r[e]==nil)then r[e]={}end table.insert(r[e],a);n=n+1;end return t,r end local function p(t,a,e)local t=string.format("%x",t)local a=string.format("%x",a)local e=string.format("%x",e)if(#t<2)then t="0"..t end if(#a<2)then a="0"..a end if(#e<2)then e="0"..e end local e="01"..e..a..t;return tonumber(e,16)end local function T(d,o,I)local n,a,r,c,m,e,t,i,l local d=d local o=o if(d>360)then d=d-360;elseif(d<0)then d=d+360;end if(o>1)then o=1;elseif(o<0)then o=0;end e=math.floor(255*I)if(e>255)then e=255;elseif(e<0)then e=0;end if(o==0)then n=e;a=e;r=e;else c=math.floor(d/60)m=d/60-c t=math.floor(e*(1-o))if(t<0)then t=0;elseif(t>255)then t=255;end i=math.floor(e*(1-m*o))if(i<0)then i=0;elseif(i>255)then i=255;end l=math.floor(e*(1-(1-m)*o))if(l<0)then l=0;elseif(l>255)then l=255;end if(c==0)then n=e;a=l;r=t;elseif(c==1)then n=i;a=e;r=t;elseif(c==2)then n=t;a=e;r=l;elseif(c==3)then n=t;a=i;r=e;elseif(c==4)then n=l;a=t;r=e;elseif(c==5)then n=e;a=t;r=i;else n=e;a=l;r=t;end end return n,a,r end local function n(t,e)reaper.SetMediaItemInfo_Value(t,"I_CUSTOMCOLOR",e);end if(s>0)then reaper.Undo_BeginBlock();local e,a=h(I)local l=math.random()*360;local t=sat or .68;local e=brightness or 1;local e=p(T(l,t,e));for a,t in pairs(a)do for a,t in ipairs(t)do n(t.mediaItem,e)end end reaper.PreventUIRefresh(-1)reaper.Undo_EndBlock(f,-1);reaper.UpdateArrange();end
