--====================================================================== 
--[[ 
* ReaScript Name: kawa_MAIN_TakeNameToTrackName. 
* Version: 2017/01/16 
* Author: kawa_ 
* Author URI: http://forum.cockos.com/member.php?u=105939 
* Repository: BitBucket - kawaCat - ReaScript-M2B 
* Repository URI: https://bitbucket.org/kawaCat/reascript-m2bpack/ 
--]] 
--====================================================================== 
local d="kawa MAIN Take Name To Track Name"local i=0;local r=200;local function l(e)local a=true;local t=reaper.CountSelectedMediaItems(i);if(t>e)then reaper.ShowMessageBox("over "..tostring(e).." clip num .\nstop process","stop.",0)a=false;end return a end if(l(r)==false)then return end local function c(e)local t=reaper.CountSelectedMediaItems(e);local d=reaper.GetProjectLength(e);local n={}local a={}local r=0;while(r<t)do local t=reaper.GetSelectedMediaItem(e,r);local l=reaper.GetMediaItemTrack(t);local e=reaper.GetMediaTrackInfo_Value(l,"IP_TRACKNUMBER");if(a[e]==nil)then a[e]={}local r=reaper.CountTrackMediaItems(l);local t=0;while(t<r)do local r=reaper.GetTrackMediaItem(l,t)local n=reaper.GetMediaItemInfo_Value(r,"D_POSITION")local o=reaper.GetMediaItemInfo_Value(r,"D_LENGTH")local l={mediaItem=r,startTime=n,length=o,endTime=n+o,mediaItemIdx=reaper.GetMediaItemInfo_Value(r,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l};table.insert(a[e],l);t=t+1;end table.sort(a[e],function(e,a)return(e.startTime>a.startTime);end);end local i=reaper.GetMediaItemInfo_Value(t,"D_POSITION")local o=reaper.GetMediaItemInfo_Value(t,"D_LENGTH")local t={mediaItem=t,startTime=i,length=o,endTime=i+o,mediaItemIdx=reaper.GetMediaItemInfo_Value(t,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l,nextItemStartTime=nil,nextMediaItem=nil};local l=d;local o=nil for a,e in ipairs(a[e])do if(e.mediaItemIdx==t.mediaItemIdx)then t.nextItemStartTime=l;t.nextMediaItem=o;end l=e.startTime;o=e;end if(n[e]==nil)then n[e]={}end table.insert(n[e],t);r=r+1;end return a,n end local function t(e)local e=reaper.GetTake(e,reaper.GetMediaItemInfo_Value(e,"I_CURTAKE"))return e;end local function l()local a,e=c(i)for a,e in pairs(e)do for e,a in ipairs(e)do local e=t(a.mediaItem)local a=a.mediaTrack if(e~=nil)then local t,e=reaper.GetSetMediaItemTakeInfo_String(e,"P_NAME","",false)local t=e:match("^.+(%..+)$")or""e=e:gsub(t,"")reaper.GetSetMediaTrackInfo_String(a,"P_NAME",e,true)break;end end end end reaper.Undo_BeginBlock();l()reaper.Undo_EndBlock(d,-1);reaper.UpdateArrange();