--====================================================================== 
--[[ 
* ReaScript Name: kawa_MAIN_ToggleLengthNext. 
* Version: 2017/01/16 
* Author: kawa_ 
* Author URI: http://forum.cockos.com/member.php?u=105939 
* Repository: BitBucket - kawaCat - ReaScript-M2B 
* Repository URI: https://bitbucket.org/kawaCat/reascript-m2bpack/ 
--]] 
--====================================================================== 
local o=0;local m=reaper.CountSelectedMediaItems(o);local c="kawa_MainClip"local d="lastToggleLength"local r=200;local function l(a)local e=true;local t=reaper.CountSelectedMediaItems(o);if(t>a)then reaper.ShowMessageBox("over "..tostring(a).." clip num .\nstop process","stop.",0)e=false;end return e end if(l(r)==false)then return end local t={"4","3","2","1","0.5","0.25","0.125"}local I="kawa MAIN Toggle Length Next"local function p(e)local t=reaper.CountSelectedMediaItems(e);local d=reaper.GetProjectLength(e);local n={}local a={}local o=0;while(o<t)do local t=reaper.GetSelectedMediaItem(e,o);local l=reaper.GetMediaItemTrack(t);local e=reaper.GetMediaTrackInfo_Value(l,"IP_TRACKNUMBER");if(a[e]==nil)then a[e]={}local t=reaper.CountTrackMediaItems(l);local r=0;while(r<t)do local t=reaper.GetTrackMediaItem(l,r)local n=reaper.GetMediaItemInfo_Value(t,"D_POSITION")local o=reaper.GetMediaItemInfo_Value(t,"D_LENGTH")local t={mediaItem=t,startTime=n,length=o,endTime=n+o,mediaItemIdx=reaper.GetMediaItemInfo_Value(t,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l};table.insert(a[e],t);r=r+1;end table.sort(a[e],function(a,e)return(a.startTime>e.startTime);end);end local r=reaper.GetMediaItemInfo_Value(t,"D_POSITION")local i=reaper.GetMediaItemInfo_Value(t,"D_LENGTH")local t={mediaItem=t,startTime=r,length=i,endTime=r+i,mediaItemIdx=reaper.GetMediaItemInfo_Value(t,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l,nextItemStartTime=nil,nextMediaItem=nil};local l=d;local r=nil for a,e in ipairs(a[e])do if(e.mediaItemIdx==t.mediaItemIdx)then t.nextItemStartTime=l;t.nextMediaItem=r;end l=e.startTime;r=e;end if(n[e]==nil)then n[e]={}end table.insert(n[e],t);o=o+1;end return a,n end local function r(a)local e=reaper.GetExtState(c,d);if(e=="")then e=t[1];end local l=a or 1 local a=1;for r,n in ipairs(t)do if(n==e)then local e=r+l;if(e>#t)then e=1;end if(e<1)then e=#t;end a=t[e];break;end end local t,e=p(o)for t,e in pairs(e)do for e,t in ipairs(e)do local e=reaper.TimeMap2_QNToTime(o,tonumber(a));local e=e-1e-5;reaper.SetMediaItemInfo_Value(t.mediaItem,"D_LENGTH",e)end end reaper.SetExtState(c,d,a,false);end if(m>0)then reaper.Undo_BeginBlock();local e=-1;r(e)reaper.Undo_EndBlock(I,-1);reaper.UpdateArrange();end
