--====================================================================== 
--[[ 
* ReaScript Name: kawa_MAIN_ColorSelectedItemHueRand. 
* Version: 2017/01/16 
* Author: kawa_ 
* Author URI: http://forum.cockos.com/member.php?u=105939 
* Repository: BitBucket - kawaCat - ReaScript-M2B 
* Repository URI: https://bitbucket.org/kawaCat/reascript-m2bpack/ 
--]] 
--====================================================================== 
local I=0 local s=reaper.CountSelectedMediaItems(I);math.randomseed(reaper.time_precise()*os.time()/1e3)local h="kawa MAIN Selected Item Hue Grad";local function p(e)local t=reaper.CountSelectedMediaItems(e);local d=reaper.GetProjectLength(e);local n={}local a={}local r=0;while(r<t)do local t=reaper.GetSelectedMediaItem(e,r);local l=reaper.GetMediaItemTrack(t);local e=reaper.GetMediaTrackInfo_Value(l,"IP_TRACKNUMBER");if(a[e]==nil)then a[e]={}local t=reaper.CountTrackMediaItems(l);local n=0;while(n<t)do local t=reaper.GetTrackMediaItem(l,n)local o=reaper.GetMediaItemInfo_Value(t,"D_POSITION")local r=reaper.GetMediaItemInfo_Value(t,"D_LENGTH")local t={mediaItem=t,startTime=o,length=r,endTime=o+r,mediaItemIdx=reaper.GetMediaItemInfo_Value(t,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l};table.insert(a[e],t);n=n+1;end table.sort(a[e],function(a,e)return(a.startTime>e.startTime);end);end local i=reaper.GetMediaItemInfo_Value(t,"D_POSITION")local o=reaper.GetMediaItemInfo_Value(t,"D_LENGTH")local t={mediaItem=t,startTime=i,length=o,endTime=i+o,mediaItemIdx=reaper.GetMediaItemInfo_Value(t,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l,nextItemStartTime=nil,nextMediaItem=nil};local l=d;local o=nil for a,e in ipairs(a[e])do if(e.mediaItemIdx==t.mediaItemIdx)then t.nextItemStartTime=l;t.nextMediaItem=o;end l=e.startTime;o=e;end if(n[e]==nil)then n[e]={}end table.insert(n[e],t);r=r+1;end return a,n end local function f(a,l,e)local t=string.format("%x",a)local a=string.format("%x",l)local e=string.format("%x",e)if(#t<2)then t="0"..t end if(#a<2)then a="0"..a end if(#e<2)then e="0"..e end local e="01"..e..a..t;return tonumber(e,16)end local function M(c,i,I)local n,l,r,o,m,e,a,d,t local c=c local i=i if(c>360)then c=c-360;elseif(c<0)then c=c+360;end if(i>1)then i=1;elseif(i<0)then i=0;end e=math.floor(255*I)if(e>255)then e=255;elseif(e<0)then e=0;end if(i==0)then n=e;l=e;r=e;else o=math.floor(c/60)m=c/60-o a=math.floor(e*(1-i))if(a<0)then a=0;elseif(a>255)then a=255;end d=math.floor(e*(1-m*i))if(d<0)then d=0;elseif(d>255)then d=255;end t=math.floor(e*(1-(1-m)*i))if(t<0)then t=0;elseif(t>255)then t=255;end if(o==0)then n=e;l=t;r=a;elseif(o==1)then n=d;l=e;r=a;elseif(o==2)then n=a;l=e;r=t;elseif(o==3)then n=a;l=d;r=e;elseif(o==4)then n=t;l=a;r=e;elseif(o==5)then n=e;l=a;r=d;else n=e;l=t;r=a;end end return n,l,r end local function a(e,a)reaper.SetMediaItemInfo_Value(e,"I_CUSTOMCOLOR",a);end if(s>0)then reaper.Undo_BeginBlock();local t,e=p(I)for t,e in pairs(e)do local n=sat or .68;local r=brightness or 1;local l=hueMove_ or 90;local t=#e;local t=l/t for e,t in ipairs(e)do local e=math.random()*360;e=e%360;local e=f(M(e,n,r));a(t.mediaItem,e);end end reaper.PreventUIRefresh(-1)reaper.Undo_EndBlock(h,-1);reaper.UpdateArrange();end
