--====================================================================== 
--[[ 
* ReaScript Name: kawa_MAIN_ColorSelectedItemHueGrad. 
* Version: 2017/01/16 
* Author: kawa_ 
* Author URI: http://forum.cockos.com/member.php?u=105939 
* Repository: BitBucket - kawaCat - ReaScript-M2B 
* Repository URI: https://bitbucket.org/kawaCat/reascript-m2bpack/ 
--]] 
--====================================================================== 
local I=0 local f=reaper.CountSelectedMediaItems(I);math.randomseed(reaper.time_precise()*os.time()/1e3)local h="kawa MAIN Selected Item Hue Grad";local function s(e)local t=reaper.CountSelectedMediaItems(e);local d=reaper.GetProjectLength(e);local r={}local a={}local o=0;while(o<t)do local l=reaper.GetSelectedMediaItem(e,o);local t=reaper.GetMediaItemTrack(l);local e=reaper.GetMediaTrackInfo_Value(t,"IP_TRACKNUMBER");if(a[e]==nil)then a[e]={}local n=reaper.CountTrackMediaItems(t);local l=0;while(l<n)do local n=reaper.GetTrackMediaItem(t,l)local o=reaper.GetMediaItemInfo_Value(n,"D_POSITION")local r=reaper.GetMediaItemInfo_Value(n,"D_LENGTH")local t={mediaItem=n,startTime=o,length=r,endTime=o+r,mediaItemIdx=reaper.GetMediaItemInfo_Value(n,"IP_ITEMNUMBER"),trackId=e,mediaTrack=t};table.insert(a[e],t);l=l+1;end table.sort(a[e],function(a,e)return(a.startTime>e.startTime);end);end local n=reaper.GetMediaItemInfo_Value(l,"D_POSITION")local i=reaper.GetMediaItemInfo_Value(l,"D_LENGTH")local t={mediaItem=l,startTime=n,length=i,endTime=n+i,mediaItemIdx=reaper.GetMediaItemInfo_Value(l,"IP_ITEMNUMBER"),trackId=e,mediaTrack=t,nextItemStartTime=nil,nextMediaItem=nil};local n=d;local l=nil for a,e in ipairs(a[e])do if(e.mediaItemIdx==t.mediaItemIdx)then t.nextItemStartTime=n;t.nextMediaItem=l;end n=e.startTime;l=e;end if(r[e]==nil)then r[e]={}end table.insert(r[e],t);o=o+1;end return a,r end local function p(e,l,t)local a=string.format("%x",e)local e=string.format("%x",l)local t=string.format("%x",t)if(#a<2)then a="0"..a end if(#e<2)then e="0"..e end if(#t<2)then t="0"..t end local e="01"..t..e..a;return tonumber(e,16)end local function M(d,c,I)local l,t,n,o,m,e,a,i,r local d=d local c=c if(d>360)then d=d-360;elseif(d<0)then d=d+360;end if(c>1)then c=1;elseif(c<0)then c=0;end e=math.floor(255*I)if(e>255)then e=255;elseif(e<0)then e=0;end if(c==0)then l=e;t=e;n=e;else o=math.floor(d/60)m=d/60-o a=math.floor(e*(1-c))if(a<0)then a=0;elseif(a>255)then a=255;end i=math.floor(e*(1-m*c))if(i<0)then i=0;elseif(i>255)then i=255;end r=math.floor(e*(1-(1-m)*c))if(r<0)then r=0;elseif(r>255)then r=255;end if(o==0)then l=e;t=r;n=a;elseif(o==1)then l=i;t=e;n=a;elseif(o==2)then l=a;t=e;n=r;elseif(o==3)then l=a;t=i;n=e;elseif(o==4)then l=r;t=a;n=e;elseif(o==5)then l=e;t=a;n=i;else l=e;t=r;n=a;end end return l,t,n end local function a(e,a)reaper.SetMediaItemInfo_Value(e,"I_CUSTOMCOLOR",a);end if(f>0)then reaper.Undo_BeginBlock();local t,e=s(I)local t=reaper.CountSelectedMediaItems(I);local r=math.random()*360;local l=sat or .68;local n=brightness or 1;local o=hueMove_ or 90;local t=t;local o=o/t for t,e in pairs(e)do for e,t in ipairs(e)do local e=r+o*e;e=e%360;local e=p(M(e,l,n));a(t.mediaItem,e);end end reaper.PreventUIRefresh(-1)reaper.Undo_EndBlock(h,-1);reaper.UpdateArrange();end
