--====================================================================== 
--[[ 
* ReaScript Name: kawa_MAIN_ColorSelectedItemHueClear. 
* Version: 2017/01/16 
* Author: kawa_ 
* Author URI: http://forum.cockos.com/member.php?u=105939 
* Repository: BitBucket - kawaCat - ReaScript-M2B 
* Repository URI: https://bitbucket.org/kawaCat/reascript-m2bpack/ 
--]] 
--====================================================================== 
local I=0 local s=reaper.CountSelectedMediaItems(I);math.randomseed(reaper.time_precise()*os.time()/1e3)local f="kawa MAIN Selected Item Hue";local function h(e)local a=reaper.CountSelectedMediaItems(e);local d=reaper.GetProjectLength(e);local i={}local t={}local r=0;while(r<a)do local l=reaper.GetSelectedMediaItem(e,r);local a=reaper.GetMediaItemTrack(l);local e=reaper.GetMediaTrackInfo_Value(a,"IP_TRACKNUMBER");if(t[e]==nil)then t[e]={}local l=reaper.CountTrackMediaItems(a);local n=0;while(n<l)do local l=reaper.GetTrackMediaItem(a,n)local r=reaper.GetMediaItemInfo_Value(l,"D_POSITION")local i=reaper.GetMediaItemInfo_Value(l,"D_LENGTH")local a={mediaItem=l,startTime=r,length=i,endTime=r+i,mediaItemIdx=reaper.GetMediaItemInfo_Value(l,"IP_ITEMNUMBER"),trackId=e,mediaTrack=a};table.insert(t[e],a);n=n+1;end table.sort(t[e],function(e,t)return(e.startTime>t.startTime);end);end local o=reaper.GetMediaItemInfo_Value(l,"D_POSITION")local n=reaper.GetMediaItemInfo_Value(l,"D_LENGTH")local a={mediaItem=l,startTime=o,length=n,endTime=o+n,mediaItemIdx=reaper.GetMediaItemInfo_Value(l,"IP_ITEMNUMBER"),trackId=e,mediaTrack=a,nextItemStartTime=nil,nextMediaItem=nil};local n=d;local l=nil for t,e in ipairs(t[e])do if(e.mediaItemIdx==a.mediaItemIdx)then a.nextItemStartTime=n;a.nextMediaItem=l;end n=e.startTime;l=e;end if(i[e]==nil)then i[e]={}end table.insert(i[e],a);r=r+1;end return t,i end local function e(e,t,l)local a=string.format("%x",e)local t=string.format("%x",t)local e=string.format("%x",l)if(#a<2)then a="0"..a end if(#t<2)then t="0"..t end if(#e<2)then e="0"..e end local e="01"..e..t..a;return tonumber(e,16)end local function e(o,i,I)local r,a,l,m,c,e,t,d,n local o=o local i=i if(o>360)then o=o-360;elseif(o<0)then o=o+360;end if(i>1)then i=1;elseif(i<0)then i=0;end e=math.floor(255*I)if(e>255)then e=255;elseif(e<0)then e=0;end if(i==0)then r=e;a=e;l=e;else m=math.floor(o/60)c=o/60-m t=math.floor(e*(1-i))if(t<0)then t=0;elseif(t>255)then t=255;end d=math.floor(e*(1-c*i))if(d<0)then d=0;elseif(d>255)then d=255;end n=math.floor(e*(1-(1-c)*i))if(n<0)then n=0;elseif(n>255)then n=255;end if(m==0)then r=e;a=n;l=t;elseif(m==1)then r=d;a=e;l=t;elseif(m==2)then r=t;a=e;l=n;elseif(m==3)then r=t;a=d;l=e;elseif(m==4)then r=n;a=t;l=e;elseif(m==5)then r=e;a=t;l=d;else r=e;a=n;l=t;end end return r,a,l end local function t(e)reaper.SetMediaItemInfo_Value(e,"I_CUSTOMCOLOR",0);end if(s>0)then reaper.Undo_BeginBlock();local a,e=h(I)for a,e in pairs(e)do for a,e in ipairs(e)do t(e.mediaItem)end end reaper.PreventUIRefresh(-1)reaper.Undo_EndBlock(f,-1);reaper.UpdateArrange();end
