--====================================================================== 
--[[ 
* ReaScript Name: kawa_MAIN_ToggleLengthPrev. 
* Version: 2017/01/16 
* Author: kawa_ 
* Author URI: http://forum.cockos.com/member.php?u=105939 
* Repository: BitBucket - kawaCat - ReaScript-M2B 
* Repository URI: https://bitbucket.org/kawaCat/reascript-m2bpack/ 
--]] 
--====================================================================== 
local o=0;local m=reaper.CountSelectedMediaItems(o);local c="kawa_MainClip"local d="lastToggleLength"local r=200;local function t(a)local e=true;local l=reaper.CountSelectedMediaItems(o);if(l>a)then reaper.ShowMessageBox("over "..tostring(a).." clip num .\nstop process","stop.",0)e=false;end return e end if(t(r)==false)then return end local l={"4","3","2","1","0.5","0.25","0.125"}local I="kawa MAIN Toggle Length Prev"local function p(e)local l=reaper.CountSelectedMediaItems(e);local d=reaper.GetProjectLength(e);local n={}local a={}local o=0;while(o<l)do local l=reaper.GetSelectedMediaItem(e,o);local t=reaper.GetMediaItemTrack(l);local e=reaper.GetMediaTrackInfo_Value(t,"IP_TRACKNUMBER");if(a[e]==nil)then a[e]={}local l=reaper.CountTrackMediaItems(t);local r=0;while(r<l)do local l=reaper.GetTrackMediaItem(t,r)local n=reaper.GetMediaItemInfo_Value(l,"D_POSITION")local o=reaper.GetMediaItemInfo_Value(l,"D_LENGTH")local l={mediaItem=l,startTime=n,length=o,endTime=n+o,mediaItemIdx=reaper.GetMediaItemInfo_Value(l,"IP_ITEMNUMBER"),trackId=e,mediaTrack=t};table.insert(a[e],l);r=r+1;end table.sort(a[e],function(a,e)return(a.startTime>e.startTime);end);end local r=reaper.GetMediaItemInfo_Value(l,"D_POSITION")local i=reaper.GetMediaItemInfo_Value(l,"D_LENGTH")local l={mediaItem=l,startTime=r,length=i,endTime=r+i,mediaItemIdx=reaper.GetMediaItemInfo_Value(l,"IP_ITEMNUMBER"),trackId=e,mediaTrack=t,nextItemStartTime=nil,nextMediaItem=nil};local t=d;local r=nil for a,e in ipairs(a[e])do if(e.mediaItemIdx==l.mediaItemIdx)then l.nextItemStartTime=t;l.nextMediaItem=r;end t=e.startTime;r=e;end if(n[e]==nil)then n[e]={}end table.insert(n[e],l);o=o+1;end return a,n end local function r(a)local e=reaper.GetExtState(c,d);if(e=="")then e=l[1];end local t=a or 1 local a=1;for r,n in ipairs(l)do if(n==e)then local e=r+t;if(e>#l)then e=1;end if(e<1)then e=#l;end a=l[e];break;end end local l,e=p(o)for l,e in pairs(e)do for e,l in ipairs(e)do local e=reaper.TimeMap2_QNToTime(o,tonumber(a));local e=e-1e-5;reaper.SetMediaItemInfo_Value(l.mediaItem,"D_LENGTH",e)end end reaper.SetExtState(c,d,a,false);end if(m>0)then reaper.Undo_BeginBlock();local e=1;r(e)reaper.Undo_EndBlock(I,-1);reaper.UpdateArrange();end
