--====================================================================== 
--[[ 
* ReaScript Name: kawa_MAIN_TakeNameToTextClip. 
* Version: 2017/01/16 
* Author: kawa_ 
* Author URI: http://forum.cockos.com/member.php?u=105939 
* Repository: BitBucket - kawaCat - ReaScript-M2B 
* Repository URI: https://bitbucket.org/kawaCat/reascript-m2bpack/ 
--]] 
--====================================================================== 
local I="kawa MAIN Take Name to Text Clip"local i=0;local r=200;local function l(e)local a=true;local t=reaper.CountSelectedMediaItems(i);if(t>e)then reaper.ShowMessageBox("over "..tostring(e).." clip num .\nstop process","stop.",0)a=false;end return a end if(l(r)==false)then return end local function d(e)local t=reaper.CountSelectedMediaItems(e);local d=reaper.GetProjectLength(e);local n={}local a={}local r=0;while(r<t)do local t=reaper.GetSelectedMediaItem(e,r);local l=reaper.GetMediaItemTrack(t);local e=reaper.GetMediaTrackInfo_Value(l,"IP_TRACKNUMBER");if(a[e]==nil)then a[e]={}local t=reaper.CountTrackMediaItems(l);local r=0;while(r<t)do local t=reaper.GetTrackMediaItem(l,r)local o=reaper.GetMediaItemInfo_Value(t,"D_POSITION")local n=reaper.GetMediaItemInfo_Value(t,"D_LENGTH")local t={mediaItem=t,startTime=o,length=n,endTime=o+n,mediaItemIdx=reaper.GetMediaItemInfo_Value(t,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l};table.insert(a[e],t);r=r+1;end table.sort(a[e],function(a,e)return(a.startTime>e.startTime);end);end local i=reaper.GetMediaItemInfo_Value(t,"D_POSITION")local o=reaper.GetMediaItemInfo_Value(t,"D_LENGTH")local t={mediaItem=t,startTime=i,length=o,endTime=i+o,mediaItemIdx=reaper.GetMediaItemInfo_Value(t,"IP_ITEMNUMBER"),trackId=e,mediaTrack=l,nextItemStartTime=nil,nextMediaItem=nil};local l=d;local o=nil for a,e in ipairs(a[e])do if(e.mediaItemIdx==t.mediaItemIdx)then t.nextItemStartTime=l;t.nextMediaItem=o;end l=e.startTime;o=e;end if(n[e]==nil)then n[e]={}end table.insert(n[e],t);r=r+1;end return a,n end local function t(a)local e=false e=reaper.APIExists("BR_EnvAlloc")if(e==false and a~=true)then reaper.ShowMessageBox("This Scripts Need SWS/S&M Extenstion. \n".."\n".."Please Check  www.sws-extension.org .","stop",0)end return e end local function a(e)local e=reaper.GetTake(e,reaper.GetMediaItemInfo_Value(e,"I_CURTAKE"))return e;end local function l()if(t()==false)then return;end local t,e=d(i)for t,e in pairs(e)do for t,e in ipairs(e)do local a=a(e.mediaItem)local t=e.mediaTrack if(a~=nil)then local a,l=reaper.GetSetMediaItemTakeInfo_String(a,"P_NAME","",false)local a=reaper.AddMediaItemToTrack(t)reaper.SetMediaItemInfo_Value(a,"D_POSITION",reaper.GetMediaItemInfo_Value(e.mediaItem,"D_POSITION"))reaper.SetMediaItemInfo_Value(a,"D_LENGTH",reaper.GetMediaItemInfo_Value(e.mediaItem,"D_LENGTH"))reaper.ULT_SetMediaItemNote(a,l);end end end end reaper.Undo_BeginBlock();l()reaper.Undo_EndBlock(I,-1);reaper.UpdateArrange();